version: '3.7'

services:
  web:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./code/public/index.php:/code/public/index.php
    links:
      - php

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    environment:
      APP_ENV: dev
      APP_SECRET: f9fa47d0ddc4a681549faafab742c16b
      APP_DEBUG: 1
    volumes:
      - ./code:/code
    links:
      - db
      - cache

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_budget
    volumes:
      - ./docker/mysql/dump:/docker-entrypoint-initdb.d

  cache:
    image: redis:5
    ports:
      - '6379:6379'
